### ISSUE TITLE
General task view improvements

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/Databases#19]
**Format:** We have converted the old XML-based task views file now to the new Markdown-based format. Please check the resulting .md file whether everything is in order or some corrections/improvements are needed. See the [corresponding documentation](https://github.com/cran-task-views/ctv/blob/main/Documentation.md) for more details.

**Update:** This would also be a good time to check the entire task whether it is up to date and correct. A write-up of the general goals and content guidelines is now summarized in the workflow for [proposing new task views](https://github.com/cran-task-views/ctv/blob/main/Proposal.md) (which was not yet available when you authored your task view). Improving your task view to conform more closely with these goals and guidelines, if necessary, would be highly appreciated.

**Co-maintainers:** In particular, we strongly encourage that all task views not only have a principal maintainer but also 1-5 co-maintainers in order to get more inspirations for extensions/improvements and share the maintenance workload. So please try to extend the list of co-maintainers, ideally also including female contributors and generally involving persons with diverse backgrounds.

**Comment by terrytangyuan** [comment]
Thanks @zeileis! If anyone else from the community is watching this issue and would like to be a co-maintainer, please reach out to me.

**Comment by coatless** [comment]
@terrytangyuan sure, more than happy to be a co-maintainer.

**Comment by terrytangyuan** [comment]
@coatless Sounds great! Feel free to submit PRs to add your name to the list of maintainers and any other edits/improvements to the existing CTV.

**Comment by zeileis** [comment]
👍
Also, you @terrytangyuan should be able to officially invite your co-maintainers to have direct access to the GitHub repository.

**Comment by coatless** [comment]
@terrytangyuan done, please see: #20 

I handled the open issues as well.

**Comment by terrytangyuan** [comment]
> 👍
> Also, you @terrytangyuan should be able to officially invite your co-maintainers to have direct access to the GitHub repository.

Great idea. Invited!
